import { after } from "next/server";
import { streamText } from "ai";
import { anthropic } from "@ai-sdk/anthropic";
import fetchArticle from "@/utils/functions/crud/fetchArticle";
import { AI_SUMMARY_CONFIG } from "@/utils/constants";

export const runtime = "edge";

// POST /api/summarize/[slug]
// Server-fetches the article by slug (raw MDX never leaves the server),
// streams a TL;DR generated by Claude Haiku back to the client.
//
// Protection:
//   - Origin allow-list (NEXT_PUBLIC_SITE_URL + localhost in dev)
//   - Best-effort per-IP rate limit (per Edge worker; swap for Upstash/KV
//     in multi-region deployments)
//   - In-memory response cache keyed by slug with TTL

const RATE_WINDOW_MS = 60_000;
const RATE_MAX_PER_WINDOW = 10;
const rateBuckets = new Map<string, number[]>();

const CACHE_TTL_MS = 60 * 60 * 1000;
const summaryCache = new Map<string, { text: string; expiresAt: number }>();

function getClientIp(req: Request): string {
    const forwarded = req.headers.get("x-forwarded-for");

    if (forwarded) {
        const first = forwarded.split(",")[0]?.trim();

        if (first) {
            return first;
        }
    }

    return req.headers.get("x-real-ip") ?? "unknown";
}

function isRateLimited(ip: string): boolean {
    const now = Date.now();
    const existing = rateBuckets.get(ip) ?? [];
    const fresh = existing.filter((t) => now - t < RATE_WINDOW_MS);

    if (fresh.length >= RATE_MAX_PER_WINDOW) {
        rateBuckets.set(ip, fresh);
        return true;
    }

    fresh.push(now);
    rateBuckets.set(ip, fresh);
    
    return false;
}

function isAllowedOrigin(req: Request): boolean {
    const origin = req.headers.get("origin");
    const referer = req.headers.get("referer");
    const isDev = process.env.NODE_ENV !== "production";

    const allowed = new Set<string>();
    const siteUrl = process.env.NEXT_PUBLIC_SITE_URL;

    if (siteUrl) {
        try {
            allowed.add(new URL(siteUrl).origin);
        }
        catch {
            // Ignore malformed URL — falls through to localhost check in dev
        }
    }

    if (isDev) {
        allowed.add("http://localhost:3000");
        allowed.add("http://127.0.0.1:3000");
    }

    if (allowed.size === 0) {
        // No allow-list configured; only permit in dev to avoid lock-out
        return isDev;
    }

    if (origin && allowed.has(origin)) {
        return true;
    }

    if (referer) {
        try {
            return allowed.has(new URL(referer).origin);
        }
        catch {
            return false;
        }
    }

    return false;
}

function readCache(slug: string): string | null {
    const entry = summaryCache.get(slug);

    if (!entry) {
        return null;
    }

    if (Date.now() > entry.expiresAt) {
        summaryCache.delete(slug);
        return null;
    }

    return entry.text;
}

function writeCache(slug: string, text: string): void {
    summaryCache.set(slug, { text, expiresAt: Date.now() + CACHE_TTL_MS });
}

function sanitizeTitle(title: string): string {
    return title.replace(/["\\`]/g, "").replace(/\s+/g, " ").trim().slice(0, 200);
}

export async function POST(
    req: Request,
    { params }: { params: Promise<{ slug: string }> }
): Promise<Response> {
    try {
        if (!isAllowedOrigin(req)) {
            return new Response("Forbidden", { status: 403 });
        }

        const ip = getClientIp(req);

        if (isRateLimited(ip)) {
            return new Response("Too Many Requests", {
                status: 429,
                headers: { "Retry-After": String(Math.ceil(RATE_WINDOW_MS / 1000)) },
            });
        }

        const { slug } = await params;

        if (!slug || typeof slug !== "string" || slug.trim() === "") {
            return new Response("Invalid slug", { status: 400 });
        }

        const normalizedSlug = slug.trim();
        const cached = readCache(normalizedSlug);

        if (cached) {
            return new Response(cached, {
                status: 200,
                headers: {
                    "Content-Type": "text/plain; charset=utf-8",
                    "X-Summary-Cache": "HIT",
                },
            });
        }

        const article = await fetchArticle(normalizedSlug);

        if (!article || typeof article.content !== "string" || article.content.trim() === "") {
            return new Response("Article not found", { status: 404 });
        }

        const content = article.content.slice(0, AI_SUMMARY_CONFIG.maxContentChars);
        const rawTitle = typeof article.title === "string" ? article.title : normalizedSlug;
        const safeTitle = sanitizeTitle(rawTitle);

        const result = streamText({
            model: anthropic(AI_SUMMARY_CONFIG.model),
            system: AI_SUMMARY_CONFIG.systemPrompt,
            temperature: AI_SUMMARY_CONFIG.temperature,
            maxOutputTokens: AI_SUMMARY_CONFIG.maxTokens,
            messages: [
                {
                    role: "user",
                    content: `Summarize the article titled: ${safeTitle}\n\nOutput only the TL;DR per the system instructions.\n\n---\n\n${content}`,
                },
            ],
        });

        after(async () => {
            try {
                const text = await result.text;

                if (text && text.trim() !== "") {
                    writeCache(normalizedSlug, text);
                }
            }
            catch (cacheErr) {
                console.error("[summarize] cache write failed:", cacheErr);
            }
        });

        const response = result.toTextStreamResponse();
        response.headers.set("X-Summary-Cache", "MISS");
        return response;
    }
    catch (err) {
        console.error("[summarize] unhandled error:", err);
        return new Response("Internal Server Error", { status: 500 });
    }
}
