export const GITHUB_USERNAME = process.env.GITHUB_USERNAME ?? "CodingAbdullah";
export const GIST_BASE_URL = process.env.GIST_BASE_URL ?? "https://mdxgists.net";

export const GITHUB_GIST_LANGUAGE_MAP: Record<string, string> = {
  'Assembly': 'asm',
  'Bash': 'bash',
  'C': 'c',
  'C#': 'csharp',
  'C++': 'cpp',
  'Cairo': 'cairo',
  'Clojure': 'clojure',
  'Crystal': 'crystal',
  'CSS': 'css',
  'Dart': 'dart',
  'Diff': 'diff',
  'Dockerfile': 'dockerfile',
  'Elixir': 'elixir',
  'Erlang': 'erlang',
  'F#': 'fsharp',
  'GLSL': 'glsl',
  'Go': 'go',
  'GraphQL': 'graphql',
  'GraphQL Schema': 'graphql',
  'Groovy': 'groovy',
  'Haml': 'haml',
  'Handlebars': 'handlebars',
  'Haskell': 'haskell',
  'HCL': 'hcl',
  'HTML': 'html',
  'INI': 'ini',
  'Java': 'java',
  'JavaScript': 'javascript',
  'JSON': 'json',
  'JSX': 'jsx',
  'Julia': 'julia',
  'Kotlin': 'kotlin',
  'Less': 'less',
  'Liquid': 'liquid',
  'Lua': 'lua',
  'Makefile': 'makefile',
  'Markdown': 'markdown',
  'MATLAB': 'matlab',
  'Maven POM': 'xml',
  'MDX': 'mdx',
  'Nginx': 'nginx',
  'Nim': 'nim',
  'OCaml': 'ocaml',
  'Perl': 'perl',
  'PHP': 'php',
  'PowerShell': 'powershell',
  'Protocol Buffer': 'protobuf',
  'Pug': 'pug',
  'Python': 'python',
  'R': 'r',
  'Ruby': 'ruby',
  'Rust': 'rust',
  'Sass': 'sass',
  'Scala': 'scala',
  'SCSS': 'scss',
  'Shell': 'bash',
  'Solidity': 'solidity',
  'SPARQL': 'sparql',
  'SQL': 'sql',
  'Svelte': 'svelte',
  'Swift': 'swift',
  'Terraform': 'terraform',
  'TOML': 'toml',
  'TSX': 'tsx',
  'TypeScript': 'typescript',
  'V': 'v',
  'Vue': 'vue',
  'Vyper': 'vyper',
  'WebAssembly': 'wasm',
  'XML': 'xml',
  'YAML': 'yaml',
  'Zig': 'zig',
};
